# YAML configuration for motors 0-3

kros:
  application:
    verbose:                False  # application-level verbosity
  uart:
    uart_id:                    3  # UART identifier (1-7)
  pixel:
    pin:                      'E1' # pin for NeoPixel
  motor_controller:
    use_closed_loop:         True
    rpm_timer_number:           2  # RPM timer number
    rpm_timer_frequency:      100  # RPM timer frequency in Hz
    pwm_frequency:          20000  # frequency for PWM to motors (20-30kHz)
    log_timer_number:           6  # log timer number
    log_timer_frequency:       20  # log timer frequency in 20Hz (50ms period)
    pid_timer_number:           3  # log timer number
    pid_timer_frequency:      100  # PID timer frequency
    max_motor_speed:          159  # maximum stated motor speed (RPM)
  zero_crossing_handler:
    verbose:                False
    enabled:                 True  # use zero-crossing handler for speed polarity transitions
    decel_rate_rpm_per_sec:   300
    accel_rate_rpm_per_sec:   300
    transition_interval_ms:    20
    stop_rpm_threshold:         5.0
    confirmation_time_ms:     100
    max_transition_time_ms:  5000
  slew_limiter:
    enabled:                 True    # use rpm and speed slew limiters
    max_delta_rpm_per_sec:     45.0  # slew limiter for RPM
    max_delta_speed_per_sec:   40.0  # slew limiter for speed
    safe_slew_threshold:       10.0  # minimum magnitude below which direction changes are allowed
  pid:
      verbose:              False
      kp:                       0.60   # proportional gain   0.51
      ki:                       0.050  # integral gain       0.050
      kd:                       0.001  # derivative gain     0.001
      setpoint:                 0.0
      min:                   -100
      max:                    100
  motors:
    motor0:
      id:                    0
      name:                "M0"
      pwm_timer:             2
      pwm_channel:           1
      pwm_pin:             'A0'
      pwm_pin_name:       'PA0'
      direction_pin:       'D0'
      direction_pin_name: 'PD0'
      encoder_pin:         'C6'
      encoder_pin_name:   'PC6'
      reverse:           False
    motor1:
      id:                    1
      name:                "M1"
      pwm_timer:             2
      pwm_channel:           2
      pwm_pin:             'A1'
      pwm_pin_name:       'PA1'
      direction_pin:       'D3'
      direction_pin_name: 'PD3'
      encoder_pin:         'C7'
      encoder_pin_name:   'PC7'
      reverse:            True
    motor2:
      id:                    2
      name:                'M2'
      pwm_timer:             2
      pwm_channel:           3
      pwm_pin:             'A2'
      pwm_pin_name:       'PA2'
      direction_pin:       'D4'
      direction_pin_name: 'PD4'
      encoder_pin:         'B0'
      encoder_pin_name:   'PB0'
      reverse:            False
    motor3:
      id:                    3
      name:                'M3'
      pwm_timer:             2
      pwm_channel:           4
      pwm_pin:             'A3'
      pwm_pin_name:       'PA3'
      direction_pin:       'D5'
      direction_pin_name: 'PD5'
      encoder_pin:         'B1'
      encoder_pin_name:   'PB1'
      reverse:            True

#EOF
