# YAML configuration for motors 0-3

kros:
  application:
    verbose:             False  # application-level verbosity
  motor_controller:
    rpm_timer_number:        2  # RPM timer number
    rpm_timer_frequency:   100  # RPM timer frequency in Hz
    pwm_frequency:       20000  # frequency for PWM to motors (20-30kHz)
    encoder_frequency:     100  # encoder frequency in Hz
    log_timer_number:        6  # log timer number
    log_timer_frequency:    20  # log timer frequency in 20Hz (50ms period)
  motors:
    motor0:
      id:                    0
      name:                "M0"
      pwm_timer:             4
      pwm_channel:           1
      pwm_pin:             'B6'
      pwm_pin_name:       'PB6'
      direction_pin:      'B12'
      direction_pin_name: 'B12'
      encoder_pin:         'C6'
      encoder_pin_name:   'PC6'
      enc_timer:             3
      enc_channel:           1
      reverse:           False
    motor1:
      id:                    1
      name:                "M1"
      pwm_timer:             4
      pwm_channel:           2
      pwm_pin:             'B7'
      pwm_pin_name:       'PB7'
      direction_pin:      'B14'
      direction_pin_name: 'B14'
      encoder_pin:         'C7'
      encoder_pin_name:   'PC7'
      enc_timer:             3
      enc_channel:           2
      reverse:            True
    motor2:
      id:                    2
      name:                'M2'
      pwm_timer:             4
      pwm_channel:           3
      pwm_pin:             'B8'
      pwm_pin_name:       'PB8'
      direction_pin:       'B3'
      direction_pin_name:  'B3'
      encoder_pin:         'B0'
      encoder_pin_name:   'PB0'
      enc_timer:             3
      enc_channel:           3
      reverse:            False
    motor3:
      id:                    3
      name:                'M3'
      pwm_timer:             4
      pwm_channel:           4
      pwm_pin:             'B9'
      pwm_pin_name:       'PB9'
      direction_pin:       'B5'
      direction_pin_name:  'B5'
      encoder_pin:         'B1'
      encoder_pin_name:   'PB1'
      enc_timer:             3
      enc_channel:           4
      reverse:            True

#EOF
