# STM32H723 YAML configuration for motors 0-3
#
# stm32_uart_slave  uart2
# rp2040_uart_slave uart1

kros:
  application:
    verbose:                False  # application-level verbosity
    impl:              'stm32h562'
#   impl:              'stm32h723'
  uart_master:
    port:           '/dev/ttyAMA0'
    baud_rate:          1_000_000  # 115200 460800 921600
    use_async_mgr:          False  # sync or async UART manager
  uart_slave_app:
    verbose:                False
    is_pyboard:              True
    uart_id:                    2  # UART identifier (1-7): 3 on STM32H723, 2 on STM32H562 (TX=PA2; RX=PA3)
  pixel:
    pin:                      'A0' # pin for NeoPixel; 'E1' on STM32H723
  display:
    enable:                 False
  motor_controller:
    use_closed_loop:         True
    enable_m0:              False  # enable motor M0
    enable_m1:              False  # enable motor M1
    enable_m2:               True  # enable motor M2
    enable_m3:              False  # enable motor M3
    pwm_timer:                  4  # PWM timer number
    rpm_timer_number:           2  # RPM timer number
    rpm_timer_frequency:      100  # RPM timer frequency in Hz
    pwm_frequency:          20000  # frequency for PWM to motors (20-30kHz)
    log_timer_number:           6  # log timer number
    log_timer_frequency:        1  # log timer frequency in 20Hz (50ms period)
    pid_timer_number:           3  # log timer number
    pid_timer_frequency:      100  # PID timer frequency
    max_motor_speed:           55  # maximum stated motor speed (RPM)
  slew_limiter:
    enabled:                False    # use rpm and speed slew limiters
    max_delta_rpm_per_sec:     30.0  # slew limiter for RPM
    max_delta_speed_per_sec:   30.0  # slew limiter for speed
    safe_threshold:            10.0
  zero_crossing_handler:
    verbose:                False
    enabled:                False  # use zero-crossing handler for speed polarity transitions
    decel_rate_rpm_per_sec:    50
    accel_rate_rpm_per_sec:    50
    transition_interval_ms:    20
    stop_rpm_threshold:         5.0
    confirmation_time_ms:     100
    max_transition_time_ms:  5000
  pid:
      verbose:              False
      kp:                       2.80   # proportional gain   0.51  (was: 0.60)
      ki:                       0.000  # integral gain       0.050 (was: 0.050)
      kd:                       0.000  # derivative gain     0.001 (was: 0.001)
      setpoint:                 0.0
      min:                   -100
      max:                    100
  motors:                          # stm32h562
    motor0:
      id:                    0
      name:                "M0"
      pwm_channel:           1
      pwm_pin:             'B6'    # pink wire
      pwm_pin_name:       'PB6'
      direction_pin:      'B12'    # white wire
      direction_pin_name: 'B12'
      encoder_pin:         'C6'    # grey wire
      encoder_pin_name:   'PC6'
      reverse:           False
    motor1:
      id:                    1
      name:                "M1"
      pwm_channel:           2
      pwm_pin:             'B7'
      pwm_pin_name:       'PB7'
      direction_pin:      'B14'
      direction_pin_name: 'B14'
      encoder_pin:         'C7'
      encoder_pin_name:   'PC7'
      reverse:            True
    motor2:
      id:                    2
      name:                'M2'
      pwm_channel:           3
      pwm_pin:             'B8'
      pwm_pin_name:       'PB8'
      direction_pin:       'B3'
      direction_pin_name:  'B3'
      encoder_pin:         'C4'    # B0: Timer 3 CH3
      encoder_pin_name:   'PC4'
      reverse:            False
    motor3:
      id:                    3
      name:                'M3'
      pwm_channel:           4
      pwm_pin:             'C2'    # B9 doesn't seem to work
      pwm_pin_name:       'PC2'
      direction_pin:       'B5'
      direction_pin_name:  'B5'
      encoder_pin:         'C5'    # B1: Timer 3 CH4
      encoder_pin_name:   'PC5'
      reverse:            True
  motors_stm32h723:                # stm32h723
    motor0:
      id:                    0
      name:                "M0"
      pwm_channel:           1
      pwm_pin:             'A0'
      pwm_pin_name:       'PA0'
      direction_pin:       'D0'
      direction_pin_name: 'PD0'
      encoder_pin:         'C6'
      encoder_pin_name:   'PC6'
      reverse:           False
    motor1:
      id:                    1
      name:                "M1"
      pwm_channel:           2
      pwm_pin:             'A1'
      pwm_pin_name:       'PA1'
      direction_pin:       'D3'
      direction_pin_name: 'PD3'
      encoder_pin:         'C7'
      encoder_pin_name:   'PC7'
      reverse:            True
    motor2:
      id:                    2
      name:                'M2'
      pwm_channel:           3
      pwm_pin:             'A2'
      pwm_pin_name:       'PA2'
      direction_pin:       'D4'
      direction_pin_name: 'PD4'
      encoder_pin:         'B0'
      encoder_pin_name:   'PB0'
      reverse:            False
    motor3:
      id:                    3
      name:                'M3'
      pwm_channel:           4
      pwm_pin:             'A3'
      pwm_pin_name:       'PA3'
      direction_pin:       'D5'
      direction_pin_name: 'PD5'
      encoder_pin:         'B1'
      encoder_pin_name:   'PB1'
      reverse:            True

#EOF
